const express=require('express')
const mongoose=require('mongoose')
const router=require('./src/routes/route')
const cors = require("cors")
const app =express()
mongoose.connect('mongodb://localhost:27017/notes').then(()=>console.log('connected')).catch(err=>console.log(err))
app.use(cors())
app.use(express.json())
app.use('/',router)
app.listen(3000,()=>{
    console.log('server started')
})